### ISSUE TITLE
kyt hub: domain

### ISSUE THREAD

**Issue by jcahill** [KytCordell/docs#2]
- [x] tld
  - [x] price limit → $30
  - [x] plus .com → N
- [x] reg
  - [x] period → max til $30 i guess
  - [x] registrar → Gandi
  - [x] registrant → Katrina Worsham
- [x] whois
  - [x] privacy → Y
  - [x] contact → Katrina Worsham

**Comment by jcahill** [comment]
see [your cv site](http://whois.domaintools.com/katrinaworsham.com) for the stock WHOIS roles, etc

**Comment by jcahill** [comment]
[What are Domain Contacts?](https://help.1and1.com/domains-c36931/manage-domains-c79822/domain-contactswhois-c37582/what-are-domain-contacts-a594899.html)

**Comment by KLWorsham** [comment]
* Price, try to keep it under $30 per domain.
* I don't know what you mean by "plus .com." It  isn't really necessary?
* Period I assume means for what period of time?
* Registrar...gandi...??? What other options do we have and what are pros/cons?
* Registrant would be me
* Privacy -> ???
* Contact -> I assume me at my main personal gmail.

**Comment by jcahill** [comment]
> I don't know what you mean by "plus .com." It isn't really necessary?

that's an answer to the question
so you knew what i meant all along, sneaky sneaky

> Period I assume means for what period of time?

yes, grabbing a longer period upfront:
* decreases the rate
* increases absolute cost
* increases time w/o worrying about maintenance or service disruptions
* increases time you're stuck with initial reg settings unless you know how to update them and/or transfer the owner, registrar, etc

> Registrar...gandi...??? What other options do we have and what are pros/cons?

registrars have deals that others don't sometimes, different rates, etc.
i'll just assume we're gonna ignore that and use gandi exclusively

> Registrant would be me

i.e. gandi handle then, kk

> Privacy -> ???

obfuscated contact details vs not. obfuscated often means more configuration fuckery with things like storefront setup, later on. not a big deal.

> Contact -> I assume me at my main personal gmail.

unless you want sysadmin to be the tech contact

**Comment by KLWorsham** [comment]
> Period
What are our options? Maybe do one year each right now? What are bundle options?

> Gandi Handle
KW2179-GANDI

> Privacy
Idgaf

>Contact
Make it me. And I will like blip u if something bad happens.
