### ISSUE TITLE
kyt hub: mail

### ISSUE THREAD

**Issue by jcahill** [KytCordell/docs#3]

**Comment by KLWorsham** [comment]
What is the question?

**Comment by jcahill** [comment]
address name. do you want to use just one @kytcordell.net and link it in the about/contact of both comics?

**Comment by KLWorsham** [comment]
Yeah let's do that. admin@kytcordell.net works.

**Comment by KLWorsham** [comment]
admin is good

**Comment by jcahill** [comment]
d-done
